### ISSUE TITLE
Crashes with Inventory Hotswap

### ISSUE THREAD

**Issue by Khodyn** [Schauweg/Smooth-Swapping#2]
Crashes when using the [Inventory Hotswap](https://www.curseforge.com/minecraft/mc-mods/inventory-hotswap) mod.

```
[09:20:03] [Render thread/FATAL]: Unreported exception thrown!
java.lang.IndexOutOfBoundsException: Index 27 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.class_2371.get(class_2371.java:47) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2813.addInventorySwap(class_2813.java:534) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2813.handler$zlb001$onInit(class_2813.java:563) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2813.<init>(class_2813.java:29) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_636.method_2906(class_636.java:428) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at com.loucaskreger.inventoryhotswap.InventoryHotswap.lambda$onClientTick$1(InventoryHotswap.java:484) ~[inventory-hotswap-fabric-1.17.1-1.3.0.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65) ~[956b2572-c14d-4c2d-9088-2245d99f69ef.jar:?]
	at net.minecraft.class_310.handler$cbe000$onEndTick(class_310.java:14573) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1806) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1081) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Schauweg** [comment]
It should be fixed with this commit d486796.
Thanks for the report!
