### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by AzrouStone** [Schauweg/Smooth-Swapping#37]
Loads Mojang Logo then crashes before loading the menu to select single player/multiplayer

Description: Rendering screen

java.lang.NoClassDefFoundError: com/terraformersmc/modmenu/api/ConfigScreenFactory
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_918.handler$hii000$onRenderItem(class_918.java:4539)
	at net.minecraft.class_918.method_23179(class_918.java)
	at net.minecraft.class_918.method_4021(class_918.java:307)
	at net.minecraft.class_918.method_4010(class_918.java:278)
	at com.simibubi.create.foundation.config.ui.OpenCreateMenuButton.method_25353(OpenCreateMenuButton.java:33)
	at net.minecraft.class_339.method_25359(class_339.java:93)
	at net.minecraft.class_4185.method_25359(class_4185.java:48)
	at net.minecraft.class_339.method_25394(class_339.java:66)
	at net.minecraft.class_437.method_25394(class_437.java:107)
	at net.minecraft.class_442.method_25394(class_442.java:333)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: com.terraformersmc.modmenu.api.ConfigScreenFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by Schauweg** [comment]
you need modmenu installed
