### ISSUE TITLE
Game crashes seemingly randomly 

### ISSUE THREAD

**Issue by NezzleGod** [Schauweg/Smooth-Swapping#57]
Crash report - https://pastebin.com/tVHDAZqq

Minecraft 1.20 Fabric

**Comment by Schauweg** [comment]
Do you remember if you were in an inventory of a mod or in a vanilla one?

**Comment by NezzleGod** [comment]
> Do you remember if you were in an inventory of a mod or in a vanilla one?

It was a vanilla inventory, inventory to chest transfer, also on a multiplayer server, it also happens not so often

**Comment by NezzleGod** [comment]
Closed accidentaly

**Comment by sternschnaube** [comment]
I had something similar, when I tried to craft a crafting table in the player crafting GUI.

java.lang.StackOverflowError: Rendering screen
	at dev.shwg.smoothswapping.Vec2.diff(Vec2.java:101)
	at dev.shwg.smoothswapping.Vec2.distance(Vec2.java:171)
	at dev.shwg.smoothswapping.config.CatmullRomWidget$CatmullRomSpline.<init>(CatmullRomWidget.java:250)
	at dev.shwg.smoothswapping.config.CatmullRomWidget.splinesFromPoints(CatmullRomWidget.java:170)
	at dev.shwg.smoothswapping.config.Config.getSplines(Config.java:23)
	at net.minecraft.class_332.renderSwap(class_332.java:3900)
	at net.minecraft.class_332.doSwap(class_332.java:3824)
	at net.minecraft.class_332.handler$gdf000$smoothswapping$onItemDraw(class_332.java:3798)
	at net.minecraft.class_332.method_51425(class_332.java)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_332.renderSwap(class_332.java:3910)
	at net.minecraft.class_332.doSwap(class_332.java:3824)
	at net.minecraft.class_332.handler$gdf000$smoothswapping$onItemDraw(class_332.java:3798)
	at net.minecraft.class_332.method_51425(class_332.java)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_332.renderSwap(class_332.java:3910)
	at net.minecraft.class_332.doSwap(class_332.java:3824)
...
(repeated alot of times)

**Comment by zjxdiu** [comment]
Same issue here, the crash report is seemingly the same; In my multiplayer server, Minecraft official launcher, crash randomly but only when transfer items from/to an inventory, including chest minecart, crafting table and barrels.

**Comment by DeshiDesu** [comment]
Happened to me on 1.20.1 multiplayer. Crash happened when transferring stacks of string from chest to inventory.

[latest.log](https://github.com/Schauweg/Smooth-Swapping/files/12373336/latest.log)

**Comment by GuyWhosBadAtCoding** [comment]
https://mclo.gs/ttSiKQS I am getting the same error, 1.20 singleplayer

**Comment by Schauweg** [comment]
this should be hopefully fixed now

**Comment by sternschnaube** [comment]
Thank you @Schauweg, I will test it soon 😊
