### ISSUE TITLE
Crash when item is removed from container while still rendering swap.

### ISSUE THREAD

**Issue by StrongSand94191** [Schauweg/Smooth-Swapping#65]
Whenever shift-clicking items into a container with a hopper underneath them, the game will crash if the item is removed from the container before the swap is finished rendering. I tested this with Dispensers and with Chests.

The image of Not Enough Crashes identifying Smooth Swapping as the cause of the crash.
<img width="1280" alt="image" src="https://github.com/Schauweg/Smooth-Swapping/assets/79473173/e1f2fc03-504f-475c-baf0-4f20c7d286e4">

The first crash that happened when items were removed from the container while the curve was still happening (had to use mclogs because crashy wasn't working): [https://mclo.gs/qhDCtpE](https://mclo.gs/qhDCtpE)

The second crash that happened when I tried to open my inventory: [https://crashy.net/2aab5945-d4d9-4fab-8433-0d4e7fbd4e12](https://crashy.net/2aab5945-d4d9-4fab-8433-0d4e7fbd4e12)

While these crash reports show that I have many other mods loaded which could also be the source of the problem, I was able to remove all mods but Smooth Swapping and Fabric API, and only the first crash still happened.

**Comment by MenacingPerson** [comment]
I just had that happen to me:

```
	at net.minecraft.class_332.handler$bbb000$smoothswapping$onItemDraw(class_332.java:798)
	at net.minecraft.class_332.method_51425(class_332.java)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_332.renderSwap(class_332.java:910)
	at net.minecraft.class_332.doSwap(class_332.java:824)
	at net.minecraft.class_332.handler$bbb000$smoothswapping$onItemDraw(class_332.java:798)
	at net.minecraft.class_332.method_51425(class_332.java)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_332.renderSwap(class_332.java:910)
	at net.minecraft.class_332.doSwap(class_332.java:824)
	at net.minecraft.class_332.handler$bbb000$smoothswapping$onItemDraw(class_332.java:798)
	at net.minecraft.class_332.method_51425(class_332.java)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_332.renderSwap(class_332.java:910)
	at net.minecraft.class_332.doSwap(class_332.java:824)
	at net.minecraft.class_332.handler$bbb000$smoothswapping$onItemDraw(class_332.java:798)
	at net.minecraft.class_332.method_51425(class_332.java)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_332.renderSwap(class_332.java:910)
	at net.minecraft.class_332.doSwap(class_332.java:824)
	at net.minecraft.class_332.handler$bbb000$smoothswapping$onItemDraw(class_332.java:798)
	at net.minecraft.class_332.method_51425(class_332.java)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at net.minecraft.class_332.renderSwap(class_332.java:910)
	at net.minecraft.class_332.doSwap(class_332.java:824)
```


This is spammed over and over again

**Comment by hschwar** [comment]
This issue also happens when shift clicking fuel into a furnace, if it is consumed before the animation is complete

**Comment by Riflusso** [comment]
I've checked all the issues and I think there are all duplicates of this issue, @ZzKingCzZ @WaterYouDoing-0 @octoshrimpy @arctlw @bunnypause @StrongSand94191 @hschwar @MenacingPerson I tried to fix it in the latest build, you can check the non-source files from the artifacts if you want and help me fix this issue [1.21.1 builds](https://github.com/Schauweg/Smooth-Swapping/actions/runs/19296820364), [1.21.8 builds](https://github.com/Schauweg/Smooth-Swapping/actions/runs/19296869125), [1.21.10 builds](https://github.com/Schauweg/Smooth-Swapping/actions/runs/19296833590)

**Comment by StrongSand94191** [comment]
i tested it on 1.21.10, i believe the issue is fixed!
